import { statPresentation } from '../dashboard/statPresentation';
export function Shimmer({ className = '', style }) { return <div aria-hidden="true" style={style} className={`animate-pulse bg-slate-100 ${className}`} />; }
export function StatCardsSkeleton(){return <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4},(_,i)=><div key={i} className="flex h-[86px] items-center rounded-xl border border-slate-100 bg-white px-4"><Shimmer className="mr-4 h-12 w-12 rounded-xl"/><div className="flex-1 space-y-2"><Shimmer className="h-3 w-24 rounded"/><Shimmer className="h-5 w-20 rounded"/><Shimmer className="h-3 w-28 rounded"/></div></div>)}</div>}
export function TableSkeleton({rows=8,columns=6}){return <div className="overflow-hidden rounded-xl border border-slate-100 bg-white"><div className="grid gap-4 border-b border-slate-100 px-4 py-3" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{Array.from({length:columns},(_,i)=><Shimmer key={i} className="h-3 rounded"/>)}</div>{Array.from({length:rows},(_,r)=><div key={r} className="grid min-h-[58px] items-center gap-4 border-b border-slate-100 px-4 py-3 last:border-0" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{Array.from({length:columns},(_,c)=><Shimmer key={c} className={`rounded ${c===0?'h-8':'h-3'}`}/>)}</div>)}</div>}
export function ChartSkeleton(){const heights=[35,58,44,72,50,82,63,76,48,68,88,57,73,45,61];return <div className="h-full rounded-xl border border-slate-100 bg-white p-4 shadow-[0_3px_18px_rgba(15,23,42,0.02)]"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-[16px] font-bold text-slate-900">Revenue Overview</h3><div className="flex items-center gap-5 text-[12px] font-semibold text-slate-500"><span>● Online Payments</span><span>● Pay at Venue</span><span>● Pending</span><span className="rounded-lg border border-slate-100 px-3 py-2">This Month</span></div></div><div className="mt-4 flex h-[205px]"><div className="flex w-10 shrink-0 flex-col justify-between pb-7 pr-2 text-right text-[11px] font-bold text-slate-400"><span>20K</span><span>15K</span><span>10K</span><span>5K</span><span>0</span></div><div className="relative min-w-0 flex-1"><div className="absolute inset-x-0 bottom-7 top-0 flex flex-col justify-between">{Array.from({length:5},(_,i)=><div key={i} className="border-t border-slate-100"/>)}</div><div className="relative z-10 flex h-full items-end justify-between gap-1 pb-7">{heights.map((h,i)=><div key={i} className="flex h-full flex-1 items-end justify-center"><Shimmer className="w-full max-w-[22px] rounded-t-[2px]" style={{height:`${h}%`}}/></div>)}</div><div className="absolute inset-x-0 bottom-0 flex justify-between text-[11px] font-bold text-slate-500"><span>Sep 1</span><span>Sep 9</span><span>Sep 17</span><span>Sep 25</span></div></div></div></div>}

export function LabeledStatCardsSkeleton({ labels = [] }) {
  return <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{labels.map((label)=>{const presentation=statPresentation[label]||statPresentation['Total Bookings'];const Icon=presentation.icon;return <div key={label} className="flex items-center rounded-xl border border-slate-100 bg-white px-4 py-4 shadow-[0_3px_18px_rgba(15,23,42,0.025)]"><div className={`mr-4 flex h-12 w-12 shrink-0 items-center justify-center rounded-xl ${presentation.iconWrapper}`}><Icon size={23} className={presentation.iconColor}/></div><div className="min-w-0 flex-1"><p className="mb-2 text-[13px] font-medium text-slate-500">{label}</p><div className="flex items-center gap-2"><Shimmer className="h-5 w-24 rounded"/><Shimmer className="h-5 w-12 rounded-full"/></div><Shimmer className="mt-2 h-3 w-32 rounded"/></div></div>})}</div>;
}
export function PaymentTableSkeleton({ columns = [] }) {
  return <div className="min-w-0 overflow-hidden rounded-xl border border-slate-100 bg-white shadow-[0_4px_20px_-4px_rgba(0,0,0,0.05)]"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:max-w-sm"><div className="h-[38px] rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-xs text-slate-400">Search by customer, phone, payment ID, booking ID...</div></div><div className="flex gap-2"><div className="h-[38px] w-24 rounded-lg border border-slate-200 bg-white"/><div className="h-[38px] w-28 rounded-lg border border-slate-200 bg-white"/><div className="h-[38px] w-32 rounded-lg border border-slate-200 bg-white"/></div></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-slate-100 text-[11px] font-bold uppercase tracking-wide text-slate-400"><th className="w-10 px-4 py-3"><input type="checkbox" disabled className="h-3.5 w-3.5 rounded border-slate-300"/></th>{columns.map(c=><th key={c} className="whitespace-nowrap px-4 py-3">{c}</th>)}</tr></thead><tbody>{Array.from({length:10},(_,r)=><tr key={r} className="h-[62px] border-b border-slate-50"><td className="px-4"><input type="checkbox" disabled className="h-3.5 w-3.5 rounded border-slate-300"/></td>{columns.map((c,i)=><td key={c} className="px-4 py-3"><div className="flex items-center gap-2">{i===1&&<Shimmer className="h-9 w-9 shrink-0 rounded-full"/>}<div className="w-full space-y-1.5"><Shimmer className={`${i===1?'h-3 w-24':'h-3 w-20'} rounded`}/>{i===1&&<Shimmer className="h-2.5 w-16 rounded"/>}</div></div></td>)}</tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 p-4 text-xs text-slate-500"><span>Showing results</span><div className="flex items-center gap-2"><span>Rows per page</span><div className="h-8 w-16 rounded-lg border border-slate-200"/><div className="h-8 w-8 rounded-lg border border-slate-200"/><div className="h-8 w-8 rounded-lg border border-slate-200"/></div></div></div>;
}
export function PayoutSummarySkeleton(){return <div className="h-full rounded-xl border border-slate-100 bg-white p-5"><div className="flex items-center justify-between"><h3 className="text-sm font-bold text-slate-900">Payout Summary</h3><span className="text-xs font-semibold text-slate-500">View Payouts</span></div><div className="mt-5 flex items-center gap-3"><Shimmer className="h-12 w-12 rounded-xl"/><div><p className="text-xs text-slate-500">Available Balance</p><Shimmer className="mt-2 h-6 w-28 rounded"/></div></div><div className="mt-4 flex h-10 items-center justify-center rounded-lg bg-slate-100 text-xs font-bold text-slate-500">Request Payout</div><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="text-[11px] text-slate-500">Next Payout</p><Shimmer className="mt-2 h-4 w-20 rounded"/></div><div><p className="text-[11px] text-slate-500">Total Paid Out</p><Shimmer className="mt-2 h-4 w-20 rounded"/></div></div></div>}
