import { ChevronDown, Search, SlidersHorizontal, WalletCards, Landmark, CalendarDays, MoreHorizontal } from 'lucide-react';
import { Shimmer } from '../skeletons/AdminSkeletons';
import { statPresentation } from '../dashboard/statPresentation';

const PAYMENT_TABLE_COLUMNS = {
  Transactions: ['Transaction ID','Customer','Booking ID','Invoice ID','Amount','Method','Status','Date & Time','Actions'],
  Invoices: ['Invoice ID','Customer','Booking ID','Date','Amount','Status','Payment Method','Actions'],
  Receipts: ['Receipt ID','Customer','Transaction ID','Invoice ID','Booking ID','Amount','Date & Time','Actions'],
};
const TAB_STAT_LABELS = {
  Transactions: ['Total Revenue','Paid Online','Pay at Venue','Pending Payments'],
  Invoices: ['Total Invoices','Total Amount','Paid Invoice Amount','Pending Invoices'],
  Receipts: ['Total Receipts','Total Amount','Receipts This Month','Average Receipt'],
};
function Stats({tab}) { return <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{TAB_STAT_LABELS[tab].map(label=>{const p=statPresentation[label]||statPresentation['Total Bookings']; const Icon=p.icon; return <div key={label} className="flex items-center rounded-xl border border-slate-100 bg-white px-4 py-4 shadow-[0_3px_18px_rgba(15,23,42,0.025)]"><div className={`mr-4 flex h-12 w-12 shrink-0 items-center justify-center rounded-xl ${p.iconWrapper}`}><Icon size={23} className={p.iconColor}/></div><div className="min-w-0 flex-1"><p className="mb-2 text-[13px] font-medium text-slate-500">{label}</p><div className="flex items-center gap-2"><Shimmer className="h-5 w-24 rounded"/><Shimmer className="h-5 w-12 rounded-full"/></div><Shimmer className="mt-2 h-3 w-32 rounded"/></div></div>})}</div> }
function Chart(){const hs=[35,58,44,72,50,82,63,76,48,68,88,57,73,45,61];return <div className="h-full rounded-xl border border-slate-100 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-[16px] font-bold text-slate-900">Revenue Overview</h3><div className="flex items-center gap-5 text-[12px] font-semibold text-slate-500"><span>● Online Payments</span><span>● Pay at Venue</span><span>● Pending</span><button className="flex items-center gap-1.5 rounded-lg border border-slate-100 px-3 py-2 text-[13px] font-bold">This Month <ChevronDown size={14}/></button></div></div><div className="mt-4 flex h-[205px]"><div className="flex w-10 flex-col justify-between pb-7 pr-2 text-right text-[11px] font-bold text-slate-400"><span>20K</span><span>15K</span><span>10K</span><span>5K</span><span>0</span></div><div className="relative flex-1"><div className="absolute inset-x-0 bottom-7 top-0 flex flex-col justify-between">{[0,1,2,3,4].map(i=><div key={i} className="border-t border-slate-100"/>)}</div><div className="relative z-10 flex h-full items-end justify-between gap-1 pb-7">{hs.map((h,i)=><Shimmer key={i} className="w-full max-w-[22px] rounded-t-[2px]" style={{height:`${h}%`}}/>)}</div><div className="absolute inset-x-0 bottom-0 flex justify-between text-[11px] font-bold text-slate-500"><span>Sep 1</span><span>Sep 9</span><span>Sep 17</span><span>Sep 25</span></div></div></div></div>}
function Payout(){return <div className="h-full rounded-xl border border-slate-100 bg-white p-4"><div className="flex items-center justify-between"><h3 className="text-[16px] font-bold">Payout Summary</h3><span className="rounded-md bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-600">View Payouts</span></div><div className="mt-3 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-lime-50 text-lime-600"><WalletCards size={22}/></div><div><p className="text-[11px] text-slate-500">Available Balance</p><Shimmer className="mt-1 h-5 w-28 rounded"/><p className="mt-1.5 text-[11px] text-slate-400">Ready for payout</p></div></div><button className="mt-4 flex h-10 w-full items-center justify-center rounded-lg bg-lime-400 text-[12px] font-bold">Request Payout</button><div className="mt-4 grid grid-cols-2 gap-3">{[[Landmark,'Total Paid Out'],[CalendarDays,'Next Payout']].map(([Icon,label])=><div key={label} className="flex items-center gap-2.5 rounded-lg border border-slate-100 p-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-50"><Icon size={17}/></div><div><p className="text-[10px] text-slate-400">{label}</p><Shimmer className="mt-1 h-3 w-16 rounded"/><Shimmer className="mt-1 h-2 w-20 rounded"/></div></div>)}</div></div>}
function Table({tab}){const columns=PAYMENT_TABLE_COLUMNS[tab];return <div className="overflow-hidden rounded-xl border border-slate-100 bg-white"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:max-w-sm"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><span className="block rounded-lg border border-slate-200 py-2.5 pl-9 pr-3 text-xs text-slate-400">Search by customer, phone, payment ID, booking ID...</span></div><div className="flex gap-2"><span className="rounded-lg border border-slate-200 px-3 py-2.5 text-xs font-semibold text-slate-600">All Dates</span>{tab!=='Receipts'&&<span className="rounded-lg border border-slate-200 px-3 py-2.5 text-xs font-semibold text-slate-600">All Statuses</span>}{tab==='Transactions'&&<span className="rounded-lg border border-slate-200 px-3 py-2.5 text-xs font-semibold text-slate-600">All Payment Methods</span>}<button className="flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200"><SlidersHorizontal size={14}/></button></div></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-slate-100 text-[11px] font-bold uppercase tracking-wide text-slate-400"><th className="w-10 px-4 py-3"><input type="checkbox" disabled/></th>{columns.map(c=><th key={c} className="whitespace-nowrap px-4 py-3">{c}</th>)}</tr></thead><tbody>{Array.from({length:10},(_,r)=><tr key={r} className="h-[62px] border-b border-slate-50"><td className="px-4"><input type="checkbox" disabled/></td>{columns.map((c)=><td key={c} className="px-4 py-3">{c==='Actions'?<MoreHorizontal size={16} className="text-slate-300"/>:<div className="flex items-center gap-2">{c==='Customer'&&<Shimmer className="h-9 w-9 shrink-0 rounded-full"/>}<div className="space-y-1.5"><Shimmer className={`h-3 rounded ${c==='Customer'?'w-24':'w-20'}`}/>{c==='Customer'&&<Shimmer className="h-2.5 w-16 rounded"/>}</div></div>}</td>)}</tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 p-4 text-xs text-slate-500"><span>Showing <Shimmer className="inline-block h-3 w-20 rounded align-middle"/> results</span><div className="flex items-center gap-2"><span>Rows per page</span><span className="rounded-lg border border-slate-200 px-3 py-2">10</span>{[1,2,3].map(x=><span key={x} className="flex h-8 w-8 items-center justify-center rounded-lg border border-slate-200">{x}</span>)}</div></div></div>}
export function PaymentsDetailsDrawerSkeleton({kind='transaction'}){return <aside className="fixed right-0 top-0 z-50 h-full w-[340px] max-w-full border-l border-slate-100 bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-base font-extrabold">{kind==='invoice'?'Invoice':kind==='receipt'?'Receipt':'Transaction'} Details</h2><span>×</span></div><div className="mt-4 flex justify-between"><Shimmer className="h-6 w-20 rounded-full"/><Shimmer className="h-3 w-24 rounded"/></div><Shimmer className="mt-4 h-8 w-32 rounded"/><Shimmer className="mt-2 h-3 w-28 rounded"/><div className="mt-4 grid grid-cols-2 gap-2"><span className="h-10 rounded-lg bg-lime-400"/><span className="h-10 rounded-lg border border-slate-200"/></div>{['Payment Information','Related Records','Customer','Venue & Booking','Timeline'].map(x=><section key={x} className="mt-5 border-t border-slate-100 pt-4"><h3 className="text-[11px] font-bold uppercase text-slate-400">{x}</h3><div className="mt-3 space-y-3">{[1,2,3].map(i=><div key={i} className="flex justify-between"><Shimmer className="h-3 w-20 rounded"/><Shimmer className="h-3 w-28 rounded"/></div>)}</div></section>)}</aside>}
export default function PaymentsPageSkeleton({tab='Transactions'}){return <><Stats tab={tab}/><section className="grid grid-cols-1 items-stretch gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]"><Chart/><Payout/></section><Table tab={tab}/></>}
